#!/usr/bin/python3

import subprocess;
print("\033[H\033[2J", end="\r");
print("\033[34m+----------------------+\033[0m");
print("\033[34m|\033[0m \033[32m1\033[0m. Boot normally     \033[34m|\033[0m");
print("\033[34m|\033[0m \033[32m2\033[0m. Poweroff          \033[34m|\033[0m");
print("\033[34m|\033[0m \033[94mPtichkaBoot 1.1\033[0m      \033[34m|\033[0m");
print("\033[34m+----------------------+\033[0m");
while True:
    com = input("boot# ")
    if com == "1":
        subprocess.run(["xterm", "./main.py"]);
    elif com == "2":
        exit();
