#!/usr/bin/python3

from os import system;
from readchar import readkey;

cur = "ptichka://home";
pages = {
  "ptichka://home": "Welcome to PtichkaWeb!\nTo search, type `g`.\nPress `h` for help.\n",
  "ptichka://notfound": "Page not found\nPress `h` for help.\n",
  "version": "PtichkaOS version 1.3\nPtichkaWeb version 2\n",
  "developers": "PtichkaOS developers:\n\tLuxidev (chelik10228)\n",
  "changelog": """PtichkaOS changelog:
  1.3\tadded command 'lsvdk' the showing all folders and all files
  1.2\tadded ptichkampv the video player using default mpv
  1.1\tadded the text browser\n"""
};

def panel():
  print(end=f"\033[107m\033[30m\033[K{cur} -- PtichkaWeb 2\033[0m");
  print(end="\033[200D\033[999B\033[A\033[107m\033[30m\033[Kg=search, q=quit, h=help\033[0m\033[999A\033[B\033[200D", flush=True);

def page():
  print(end=pages[cur], flush=True);

def clear():
  print(end="\033[H\033[2J", flush=True);

def search():
  return input("\033[999BSearch: ");

while (1):
  clear();
  panel();
  page();
  k = readkey();
  if (k == 'g'):
    new = search();
    if (new in pages):
      cur = new;
    else:
      cur = "ptichka://notfound";
    clear();
  elif (k == 'q'):
    clear();
    exit(0);
  elif (k == 'h'):
    cur = "ptichka://home";
    system("less pweb-help.txt");

