#!/usr/bin/python3
import time;
print("Welcome to PtichkaWeb");
print("A simple text browser for PtichkaOS");
while True:
	search = input("Search: ");
	if search == "changelog ptichkaos":
		print("Searching...");
		time.sleep(1);
		print("\033[H\033[2J", end="\r");
		print("Searched to:", search);
		print("ChangeLog PtichkaOS: ");
		print("  added ptichkampv the video player using default mpv");
	elif search == "developers ptichkaos":
		print("Searching...");
		time.sleep(1);
		print("\033[H\033[2J", end="\r");
		print("Searched to:", search);
		print("Developers PtichkaOS: ");
		print("  Luxidev");
	elif search == "version ptichkaos":
		print("Searching...");
		time.sleep(1);
		print("\033[H\033[2J", end="\r");
		print("Searched to:", search);
		print("Version PtichkaOS: ");
		print("  1.2");
	else:
		print("Nothing not found.");
